Filipino Translation - 1094 Translated Words
cakephp-tl/docs pull request #3
Opened 2018-02-25 10:29 UTC by robin-ho

components.rst = 742 translated words
middleware.rst = 352 translated words
Note : Code text and computer code text are not counted as translated words.

2018-02-25 10:56 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
> +iba-ibang mga komon na mga gawain. Maaari ka ring lumikha ng sarili mong mga komponent. Kung makikita mo
-iba-ibang mga karaniwang mga gawain.

2018-02-25 10:57 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
> +isaalang-alang ang paglikha ng iyong sariling komponent na naglalaman ng functionality. Paglilikha ng
- Ang paglilikha ng

2018-02-25 10:57 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
> +kanatana para sa bawat komponent:
- kabanata

2018-02-25 10:58 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
- na pamamaraan
- na array

2018-02-25 10:59 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
> +ito ay natapos sa iyong controller na ``beforeFilter()`` pamamaraan. Ang itaas maaari
- na pamamaraan
- Ang itaas ay maaari

2018-02-25 11:00 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
>  which is accessible with ``config()``.
Please translate this one

2018-02-25 11:01 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
> +Pag-alias ng mga Komponents
remove s for Komponents

2018-02-25 11:01 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
> +Isang komon na setting na gamitin ay ang ``className`` na opsyon, na kung saan ay nagpapahintulot sa iyo na
- Isang karaniwang setting na gamitin

2018-02-25 11:03 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
> +palitan ang ``$this->Auth`` o ibang komon na Component na reperensiya na may pasadyang
- o ibang karaniwan na Component na nagrereperensiya na may pasadyang

2018-02-25 11:07 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
> +        // Idagdag ang iyong code para sapawan ang core AuthComponent
- para i-override ang

2018-02-25 11:08 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
> +    ikaw nag-load ng iyong komponent.
- ka nag-load ng iyong komponent.

2018-02-25 11:10 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
> +Sa sandaling iyon ay kasama ang ilang mga komponent sa iyong controller, ginagamit sila ay masyadong
- controller, ang paggamit ng mga ito ay

2018-02-25 11:12 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
> +    mga property na naghahati sila ng parehong 'namespace'. Tiyakin na hindi magbigay ng
- mga property na ibinabahagi nila sa parehong

2018-02-25 11:17 UTC, mervinsantillanvillaceran commented on tl/controllers/components.rst
> +Sa sandaling ang aming komponent ay natapos, maaari nating gamitin ito sa mga controller ng ating aplikasyon
- Sa sandaling ang ating komponent

2018-02-25 11:19 UTC, smervs commented on tl/controllers/components.rst
> +component, kung saan maaaring maka-access ng instance para nito::
- ng instance nito::

2018-02-25 11:21 UTC, smervs commented on tl/controllers/components.rst
> +sa Component::
- ng Component

2018-02-25 11:21 UTC, smervs commented on tl/controllers/components.rst
> +Ang itaas ay pumasa sa array na naglalaman ng katumpakan at randomGenerator sa
- ay papasa ng array na naglalaman

2018-02-25 11:26 UTC, mervinsantillanvillaceran commented on tl/controllers/middleware.rst
> +ang iyong aplikasyon ay nagtatapos sa gitna, at ang middleware ay is naka-wrap sa app
remove is

2018-02-25 11:27 UTC, mervinsantillanvillaceran commented on tl/controllers/middleware.rst
> +ay ihiling para sa isang plugin na imahe sa panahon sa development.
- sa panahon ng development.

2018-02-25 11:29 UTC, mervinsantillanvillaceran commented on tl/controllers/middleware.rst
> +hiling at tugon na mga interface. Dahil ang CakePHP ay isang pinakikinabangan ang PSR-7
- na hiling at tugon

2018-02-25 11:30 UTC, mervinsantillanvillaceran commented on tl/controllers/middleware.rst
> +Ang CakePHP ay nagbibigay ng ilang mga middleware para i-handle ang komon na mga gawain sa web na mga aplikasyon:
- para i-handle ang karaniwang mga gawain

2018-02-25 11:40 UTC, smervs requested changes
Please check the following comments

2018-02-25 11:40 UTC, mervinsantillanvillaceran commented on tl/controllers/middleware.rst
> +  manipulahin ang naka-encrypt na mga cookie na kung sakali kailangan mong manipulahin ang cookie na may
- sakali na kailangan mong

2018-02-25 12:09 UTC, robin-ho commented on tl/controllers/components.rst
> +iba-ibang mga komon na mga gawain. Maaari ka ring lumikha ng sarili mong mga komponent. Kung makikita mo
done change

2018-02-25 12:10 UTC, robin-ho commented on tl/controllers/components.rst
> +isaalang-alang ang paglikha ng iyong sariling komponent na naglalaman ng functionality. Paglilikha ng
done change

2018-02-25 12:10 UTC, robin-ho commented on tl/controllers/components.rst
> +kanatana para sa bawat komponent:
done change

2018-02-25 12:11 UTC, robin-ho commented on tl/controllers/components.rst
done change

2018-02-25 12:11 UTC, robin-ho commented on tl/controllers/components.rst
> +ito ay natapos sa iyong controller na ``beforeFilter()`` pamamaraan. Ang itaas maaari
done change

2018-02-25 12:12 UTC, robin-ho commented on tl/controllers/components.rst
>  which is accessible with ``config()``.
done translating

2018-02-25 12:12 UTC, robin-ho commented on tl/controllers/components.rst
> +Pag-alias ng mga Komponents
done change

2018-02-25 12:13 UTC, robin-ho commented on tl/controllers/components.rst
> +Isang komon na setting na gamitin ay ang ``className`` na opsyon, na kung saan ay nagpapahintulot sa iyo na
done change

2018-02-25 12:13 UTC, robin-ho commented on tl/controllers/components.rst
> +palitan ang ``$this->Auth`` o ibang komon na Component na reperensiya na may pasadyang
done change

2018-02-25 12:14 UTC, robin-ho commented on tl/controllers/components.rst
> +        // Idagdag ang iyong code para sapawan ang core AuthComponent
done change

2018-02-25 12:14 UTC, robin-ho commented on tl/controllers/components.rst
> +    ikaw nag-load ng iyong komponent.
done change

2018-02-25 12:15 UTC, robin-ho commented on tl/controllers/components.rst
> +Sa sandaling iyon ay kasama ang ilang mga komponent sa iyong controller, ginagamit sila ay masyadong
done change

2018-02-25 12:16 UTC, robin-ho commented on tl/controllers/components.rst
> +    mga property na naghahati sila ng parehong 'namespace'. Tiyakin na hindi magbigay ng
done change

2018-02-25 12:16 UTC, robin-ho commented on tl/controllers/components.rst
> +Sa sandaling ang aming komponent ay natapos, maaari nating gamitin ito sa mga controller ng ating aplikasyon
done change

2018-02-25 12:17 UTC, robin-ho commented on tl/controllers/components.rst
> +component, kung saan maaaring maka-access ng instance para nito::
done change

2018-02-25 12:17 UTC, robin-ho commented on tl/controllers/components.rst
> +sa Component::
done change

2018-02-25 12:18 UTC, robin-ho commented on tl/controllers/components.rst
> +Ang itaas ay pumasa sa array na naglalaman ng katumpakan at randomGenerator sa
done change

2018-02-25 12:19 UTC, robin-ho commented on tl/controllers/middleware.rst
> +ang iyong aplikasyon ay nagtatapos sa gitna, at ang middleware ay is naka-wrap sa app
done change

2018-02-25 12:20 UTC, robin-ho commented on tl/controllers/middleware.rst
> +ay ihiling para sa isang plugin na imahe sa panahon sa development.
done change

2018-02-25 12:20 UTC, robin-ho commented on tl/controllers/middleware.rst
> +hiling at tugon na mga interface. Dahil ang CakePHP ay isang pinakikinabangan ang PSR-7
done change

2018-02-25 12:21 UTC, robin-ho commented on tl/controllers/middleware.rst
> +Ang CakePHP ay nagbibigay ng ilang mga middleware para i-handle ang komon na mga gawain sa web na mga aplikasyon:
done change

2018-02-25 12:21 UTC, mind-blast commented on tl/controllers/middleware.rst
> +  manipulahin ang naka-encrypt na mga cookie na kung sakali kailangan mong manipulahin ang cookie na may
done change

2018-02-25 12:22 UTC, robin-ho commented
I have revised some of your suggested words. Thank you for the proof read.

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/components.rst
> +sa sarili na gusto mong i-copy at paste ang mga bagay sa pagitan ng mga controller, dapat mo
dapat mong isaalang-alang ang paglikha ng iyong

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/components.rst
> +mga component ay nagpapanatili ng controller code na malinis at nagpapahintulot sa iyo upang gamitin ang code sa pagitan
Ang paglilikha ng mga komponento ay nagpapanitling malinis sa controller ng code at

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/components.rst
> +Marami sa pangunahing mga komponent ay nangangailangan ng configuration. Ilang mga halimbawa sa mga komponent
kumpigurasyon

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/components.rst
> +na property na may constructor configuration upang lumikha sa ``$_config`` na property
na katangian na may kumpigurasyon ng constructor para malikha ang ``$_config`` na katangian

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/components.rst
> +Isang karaniwang setting na gamitin ay ang ``className`` na opsyon, na kung saan ay nagpapahintulot sa iyo na
na gagamitin

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/components.rst
> +i-alias ang mga komponent. Ang feature na ito ay kapaki-pakinabang kapag kailangan mong
Ang katangiang ito ay

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/components.rst
> +    Tandaan na ang mga komponent na iyon ay naka-load ng nauna ay hindi malampasan
Isaisip na ang mga komponentong naunang naka-load ay hindi makakalimot sa mga natawag na mga callback.

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/components.rst
> +    na mga callback na pagiging pagtawag, maaari mong kailangan na tumawag sa kanila ng mano-mano depende kung kailan
na mga callback na tinatawag

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/components.rst
> +simple. Sa bawat component ikaw ay makagamit sa nakalantad bilang isang property ng iyong controller. Kung
Sa bawat komponentong nagamit mo ay nakalantad bilang isang katangian

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/components.rst
> +    komponent at isang modelo na parehong pangalan.
Tiyakin na hindi magbigay ng parehong pangalan sa komponento at sa isang modelo.

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/components.rst
> +    Lahat ng mga component ay dapat mag-extend sa :php:class:`Cake\\Controller\\Component`. Pagkakamali
Ang pakakalimot sa paggawa nito ay mag-trigger sa isang exception.

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/components.rst
> +Ang mga Component ay nag-aalok ng ilang mga hiling sa cycle ng buhay na mga callback na nagpapahintulot sa kanila upang
Ang mga komponento ay nag-aalok rin ng iilang mga

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/middleware.rst
> +composable na mga layer sa Hiling na paghahawak, o sagot sa building na logic. Biswal,
mga suson ng paghawak sa kahilingan, o lohika sa pagbuo ng sagot.

2018-02-26 01:28 UTC, severinolorillajr commented on tl/controllers/middleware.rst
> +na middleware. Bawat middleware ay maaring alinman ay makadelegado ng hiling/sagot sa susunod na
Bawat middleware ay maaaring mag-delegate sa hiling/sagot sa sunod na suson, o magbalik ng sagot.

2018-02-26 01:53 UTC, robin-ho commented on tl/controllers/components.rst
> +sa sarili na gusto mong i-copy at paste ang mga bagay sa pagitan ng mga controller, dapat mo
done change

2018-02-26 01:55 UTC, robin-ho commented on tl/controllers/components.rst
> +mga component ay nagpapanatili ng controller code na malinis at nagpapahintulot sa iyo upang gamitin ang code sa pagitan
done change

2018-02-26 01:57 UTC, robin-ho commented on tl/controllers/components.rst
> +Marami sa pangunahing mga komponent ay nangangailangan ng configuration. Ilang mga halimbawa sa mga komponent
done change

2018-02-26 01:57 UTC, robin-ho commented on tl/controllers/components.rst
> +na property na may constructor configuration upang lumikha sa ``$_config`` na property
done change

2018-02-26 01:58 UTC, robin-ho commented on tl/controllers/components.rst
> +Isang karaniwang setting na gamitin ay ang ``className`` na opsyon, na kung saan ay nagpapahintulot sa iyo na
done change

2018-02-26 01:58 UTC, robin-ho commented on tl/controllers/components.rst
> +i-alias ang mga komponent. Ang feature na ito ay kapaki-pakinabang kapag kailangan mong
done change

2018-02-26 01:59 UTC, robin-ho commented on tl/controllers/components.rst
> +    Tandaan na ang mga komponent na iyon ay naka-load ng nauna ay hindi malampasan
done change

2018-02-26 02:01 UTC, robin-ho commented on tl/controllers/components.rst
> +    na mga callback na pagiging pagtawag, maaari mong kailangan na tumawag sa kanila ng mano-mano depende kung kailan
done change

2018-02-26 02:02 UTC, robin-ho commented on tl/controllers/components.rst
> +simple. Sa bawat component ikaw ay makagamit sa nakalantad bilang isang property ng iyong controller. Kung
done change

2018-02-26 02:02 UTC, robin-ho commented on tl/controllers/components.rst
> +    komponent at isang modelo na parehong pangalan.
done change

2018-02-26 02:04 UTC, robin-ho commented on tl/controllers/components.rst
> +    Lahat ng mga component ay dapat mag-extend sa :php:class:`Cake\\Controller\\Component`. Pagkakamali
done change

2018-02-26 02:04 UTC, robin-ho commented on tl/controllers/components.rst
> +Ang mga Component ay nag-aalok ng ilang mga hiling sa cycle ng buhay na mga callback na nagpapahintulot sa kanila upang
done change

2018-02-26 02:06 UTC, robin-ho commented on tl/controllers/middleware.rst
> +composable na mga layer sa Hiling na paghahawak, o sagot sa building na logic. Biswal,
done change

2018-02-26 02:06 UTC, robin-ho commented on tl/controllers/middleware.rst
> +na middleware. Bawat middleware ay maaring alinman ay makadelegado ng hiling/sagot sa susunod na
done change

2018-02-26 02:07 UTC, robin-ho commented
@severinolorillajr thanks for the proof read , done changing suggested words. Thank you.

2018-02-26 02:11 UTC, merged